services:
  ui:
    container_name: saas23-1-ui
    restart: always
    build: ./ui
    depends_on:
      - server
    volumes:
      - /usr/src/app/node_modules
      - ./ui:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  server:
    container_name: saas23-1-server
    restart: always
    build: ./server
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  authenticator:
    container_name: saas23-1-authenticator
    restart: always
    build: 
      context:  ./server
      dockerfile: ./authentication-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  credithandler:
    container_name: saas23-1-credit-handler
    restart: always
    build: 
      context:  ./server
      dockerfile: ./credits-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  mongodb:
    container_name: saas23-1-db
    image: docker.io/mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - SaaS23-1-myCharts

  nginx:
    container_name: saas23-1-nginx
    restart: always
    depends_on:
      - server
      - ui
    build: ./nginx
    ports: 
      - '3000:80'
    networks:
      - SaaS23-1-myCharts


networks:
  SaaS23-1-myCharts:
    driver: bridge

volumes:
  mongodb-data:
    driver: local