services:
  ui:
    container_name: saas23-1-ui
    restart: always
    build: ./ui
    depends_on:
      - server
    volumes:
      - /usr/src/app/node_modules
      - ./ui:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  server:
    container_name: saas23-1-server
    restart: always
    build: ./server
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  authenticator:
    container_name: saas23-1-authenticator
    restart: always
    build: 
      context:  ./server
      dockerfile: ./authentication-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  credithandler:
    container_name: saas23-1-credit-handler
    restart: always
    build: 
      context:  ./server
      dockerfile: ./credits-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  previewhandler:
    container_name: saas23-1-preview-handler
    restart: always
    build: 
      context:  ./server
      dockerfile: ./preview-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  templatehandler:
    container_name: saas23-1-template-handler
    restart: always
    build: 
      context:  ./server
      dockerfile: ./template-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  downloader:
    container_name: saas23-1-downloader
    restart: always
    build: 
      context:  ./server
      dockerfile: ./download-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  exporter:
    container_name: saas23-1-exporter
    restart: always
    build: 
      context:  ./server
      dockerfile: ./export-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts
    environment:
      - OPENSSL_CONF=/etc/ssl
      - ACCEPT_HIGHCHARTS_LICENSE=fuckyou
      - HIGHCHARTS_VERSION=10.3.3

  validator:
    container_name: saas23-1-validator
    restart: always
    build: 
      context:  ./server
      dockerfile: ./validate-service/Dockerfile
    depends_on:
      - mongodb
    external_links:
      - mongodb
    volumes: 
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    networks:
      - SaaS23-1-myCharts

  mongodb:
    container_name: saas23-1-db
    image: docker.io/mongo
    restart: always
    ports:
      - '27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - SaaS23-1-myCharts

  nginx:
    container_name: saas23-1-nginx
    restart: always
    depends_on:
      - server
      - ui
    build: ./nginx
    ports: 
      - '4007:80'
    networks:
      - SaaS23-1-myCharts


networks:
  SaaS23-1-myCharts:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
