services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    external_links:
      - nginx-c
    volumes:
      - ./:/usr/src/app
    hostname: ui
  server:
    restart: always
    build: ./server
    ports:
      - '3001:3001'
    external_links:
      - mongo
      - nginx-c
    volumes: 
      - ./:/usr/src/app
  mongo:
    image: docker.io/mongo
    exposes:
      - '27017:27017'
  nginx-c:
    links:
      - "ui:ui"
      - "server:server"

    build: ./nginx
    ports: 
      - '8000:8000'
